#!/bin/bash          
#                    
/work/00303/tg455757/stampede2/M1_101214/scripts/ROIVIS/ver02/run_wrapROIs7_parallel.sh /work/00303/tg455757/stampede2/M1_101214/scripts/MTLAB2/v81 /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/roivis_input1/roivis_config.txt /tmp/target/roivis_output1 0 1 2 10 & 

/work/00303/tg455757/stampede2/M1_101214/scripts/ROIVIS/ver02/run_wrapROIs7_parallel.sh /work/00303/tg455757/stampede2/M1_101214/scripts/MTLAB2/v81 /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/roivis_input1/roivis_config.txt /tmp/target/roivis_output1 1 1 2 10 & 

wait


#!/bin/bash          
#                    
/work/00303/tg455757/stampede2/M1_101214/scripts/ROIVIS/ver02/run_wrapROIs7_parallel.sh /work/00303/tg455757/stampede2/M1_101214/scripts/MTLAB2/v81 /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/roivis_input1/roivis_config.txt /tmp/target/roivis_output1 0 7 2 10 & 

/work/00303/tg455757/stampede2/M1_101214/scripts/ROIVIS/ver02/run_wrapROIs7_parallel.sh /work/00303/tg455757/stampede2/M1_101214/scripts/MTLAB2/v81 /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/roivis_input1/roivis_config.txt /tmp/target/roivis_output1 1 7 2 10 & 

wait


