#!/bin/bash
#
jobid=
jobdetailsfile=/home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/jobdetails.txt
scancel $jobid
temp1=`date +%s`
echo "jobqueuesubmission_end_stampede2a_seconds=$temp1" >> $jobdetailsfile
temp1=`date -u`
echo "jobqueuesubmission_end_stampede2a_utc=$temp1" >> $jobdetailsfile
echo "jobstate_stampede2a=cancelled" >> $jobdetailsfile
