#!/bin/bash          
#                    
cd /tmp/target/roivis_output1
find . -name '*' -print | zip Roivis.zip -@
cp Roivis.zip /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/roivis_output1/
find ./ -type f -print0 | xargs -0 rm -f
wait


