#!/bin/bash          
#                    

rm -f -R /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/03_registration

rm -f -R /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/03_registration/02_air_lddmm/atlas*/4_deformations/*.*

rm -f -R /home1/02684/lddmmpro/process_queue/0447e9a5a94ffa9bf30089063b727ab2/registered/allAtlases/06_registration/02_air_lddmm/atlas*/4_deformations/*.*

